"""
Configuration settings for Enterprise Wi-Fi Security Analysis System
"""
from datetime import datetime

# ── AI Configuration ──────────────────────────────────────────────────────────
# Get your FREE Gemini API key at: https://aistudio.google.com
GEMINI_API_KEY = ""   # <-- paste your Gemini API key here

# App secret key for session management
SECRET_KEY = "wifi-security-analyzer-secret-2024"

# Company Branding
COMPANY_NAME = "SecureNet Analytics"
COMPANY_LOGO = None  # Path to logo image if available
REPORT_FOOTER = f"Generated by {COMPANY_NAME} - Confidential"

# Risk Scoring Weights
RISK_WEIGHTS = {
    'encryption_strength': 0.30,
    'signal_quality': 0.15,
    'vulnerability_count': 0.25,
    'compliance_score': 0.20,
    'threat_indicators': 0.10
}

# Risk Level Thresholds (0-100 scale)
RISK_THRESHOLDS = {
    'safe': (0, 30),
    'medium': (31, 60),
    'dangerous': (61, 100)
}

# Compliance Standards
COMPLIANCE_STANDARDS = {
    'PCI-DSS': {
        'name': 'Payment Card Industry Data Security Standard',
        'version': '4.0',
        'requirements': [
            {
                'id': '4.2.1',
                'description': 'Strong cryptography and security protocols',
                'check': 'encryption_wpa3_or_wpa2_aes'
            },
            {
                'id': '2.2.4',
                'description': 'Configure system security parameters',
                'check': 'no_default_credentials'
            },
            {
                'id': '11.2.1',
                'description': 'Perform quarterly wireless analyzer scans',
                'check': 'rogue_ap_detection'
            }
        ]
    },
    'HIPAA': {
        'name': 'Health Insurance Portability and Accountability Act',
        'version': 'Security Rule',
        'requirements': [
            {
                'id': '164.312(a)(2)(iv)',
                'description': 'Encryption and Decryption',
                'check': 'encryption_wpa3_or_wpa2_aes'
            },
            {
                'id': '164.308(a)(1)(ii)(D)',
                'description': 'Information System Activity Review',
                'check': 'network_monitoring_enabled'
            },
            {
                'id': '164.312(e)(1)',
                'description': 'Transmission Security',
                'check': 'secure_transmission_protocols'
            }
        ]
    },
    'ISO27001': {
        'name': 'ISO/IEC 27001:2022 Information Security',
        'version': '2022',
        'requirements': [
            {
                'id': 'A.8.24',
                'description': 'Use of cryptography',
                'check': 'strong_encryption_enabled'
            },
            {
                'id': 'A.8.22',
                'description': 'Segregation of networks',
                'check': 'network_segmentation'
            },
            {
                'id': 'A.8.20',
                'description': 'Networks security',
                'check': 'wireless_security_controls'
            }
        ]
    }
}

# Encryption Standards
ENCRYPTION_RATINGS = {
    'WPA3': {'score': 100, 'level': 'Excellent'},
    'WPA2-AES': {'score': 85, 'level': 'Good'},
    'WPA2-TKIP': {'score': 60, 'level': 'Fair'},
    'WPA': {'score': 30, 'level': 'Poor'},
    'WEP': {'score': 10, 'level': 'Critical'},
    'Open': {'score': 0, 'level': 'Critical'}
}

# Known Vulnerabilities Database
KNOWN_VULNERABILITIES = {
    'KRACK': {
        'cve': 'CVE-2017-13077',
        'name': 'Key Reinstallation Attack',
        'severity': 'High',
        'affects': ['WPA2'],
        'description': 'Allows attackers to decrypt Wi-Fi traffic'
    },
    'DragonBlood': {
        'cve': 'CVE-2019-13377',
        'name': 'WPA3 Dragonfly Handshake Vulnerability',
        'severity': 'Medium',
        'affects': ['WPA3'],
        'description': 'Side-channel information leakage'
    },
    'FragAttacks': {
        'cve': 'CVE-2020-24586',
        'name': 'Fragmentation and Aggregation Attacks',
        'severity': 'Medium',
        'affects': ['WPA2', 'WPA3'],
        'description': 'Design flaws in Wi-Fi standard'
    }
}

# Signal Strength Ratings (dBm)
SIGNAL_STRENGTH_RATINGS = {
    'excellent': (-50, 0),
    'good': (-60, -50),
    'fair': (-70, -60),
    'poor': (-80, -70),
    'very_poor': (-100, -80)
}

# Threat Detection Patterns
THREAT_PATTERNS = {
    'evil_twin': {
        'name': 'Evil Twin Attack',
        'indicators': ['duplicate_ssid', 'stronger_signal', 'different_bssid']
    },
    'deauth_attack': {
        'name': 'Deauthentication Attack',
        'indicators': ['high_deauth_rate', 'connection_drops']
    },
    'mitm': {
        'name': 'Man-in-the-Middle',
        'indicators': ['arp_spoofing', 'dns_hijacking', 'ssl_stripping']
    },
    'rogue_ap': {
        'name': 'Rogue Access Point',
        'indicators': ['unauthorized_ap', 'corporate_ssid_clone']
    }
}

# Report Configuration
REPORT_CONFIG = {
    'title': 'Wi-Fi Security Analysis Report',
    'page_size': 'A4',
    'margins': {
        'top': 72,
        'bottom': 72,
        'left': 72,
        'right': 72
    },
    'colors': {
        'primary': '#1a237e',      # Dark blue
        'secondary': '#0d47a1',    # Medium blue
        'success': '#2e7d32',      # Green
        'warning': '#f57c00',      # Orange
        'danger': '#c62828',       # Red
        'text': '#212121',         # Dark gray
        'light_bg': '#f5f5f5'      # Light gray
    },
    'fonts': {
        'title': 'Helvetica-Bold',
        'heading': 'Helvetica-Bold',
        'body': 'Helvetica',
        'code': 'Courier'
    }
}

# Database Configuration
DATABASE_CONFIG = {
    'path': 'wifi_security.db',
    'retention_days': 90,  # Keep scan history for 90 days
    'backup_enabled': True
}

# Chart Configuration
CHART_CONFIG = {
    'style': 'seaborn-v0_8-darkgrid',
    'figure_size': (10, 6),
    'dpi': 100,
    'colors': ['#1a237e', '#0d47a1', '#1976d2', '#42a5f5', '#90caf9']
}

# API Configuration
API_CONFIG = {
    'rate_limit': 100,  # requests per hour
    'timeout': 30,      # seconds
    'max_scan_duration': 60  # seconds
}
